# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    app.watch_manager:
        class: AppBundle\Service\WatchManager
        arguments: [] # register a data provider service and inject it here
    app.watch_controller:
        class: AppBundle\Controller\WatchController
        arguments: ["@app.watch_manager"]
